- name: Copy RPM file with owner and permissions
  ansible.builtin.copy:
    src: sqlchk.rpm
    dest: /root/
    owner: root
    group: root
    mode: '0644'
  when: rpm_package is defined

- name: Install package RPM
  yum:
     name: /root/sqlchk.rpm
     state: present
  when: rpm_package is defined

- name: Copy Deb file with owner and permissions
  ansible.builtin.copy:
    src: sqlchk.deb
    dest: /root/
    owner: root
    group: root
    mode: '0644'
  when: deb_package is defined

- name: Install deb package
  apt:
    deb: /root/sqlchk.deb
  become: true
